version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: /bin/sh -c "php artisan serve --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql
    tty: true
    stdin_open: true
    environment:
      DATABASE_HOST: mysql
      DATABASE_USERNAME: docker
      DATABASE_PASSWORD: docker
      DATABASE_PORT: 3306
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel_development
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
volumes:
  mysql-volume:
